### ISSUE TITLE
The wrapper script for the standalone game does not work

### ISSUE THREAD

**Issue by gianluca-nitti** [qwc/terasology-packaging#7]
I downloaded `terasology_1.4.0_all.deb` and installed it with `dpkg`, but I can't start the game with the `terasology` command (which is the bash script at `/usr/bin/terasology`); I get the following error message:
```
Error: Unable to access jarfile libs/Terasology.jar
```
No problems if I start with `/opt/terasology/run_linux.sh`.

The script in the launcher package (put at `/usr/bin/terasology-launcher` after installing `terasology-launcher_193_all.deb`), on the other hand, works perfectly.

My distribution is Ubuntu 16.04.

**Comment by qwc** [comment]
I already know why this error appears, I thought I could just make a soft link to the `run_linux.sh` script, but that script isn't as intelligent as the script of the launcher, so I have to put another script in front of it.

**Comment by qwc** [comment]
I've committed a fix, when you have time, maybe try to test it through the repo.

**Comment by gianluca-nitti** [comment]
Perfect, I tested and it works flawlessly now.

I think this can be closed.
